import serial
import time


ser = serial.Serial('/dev/ttyACM0')  # open serial port
print(ser.name)         # check which port was really used

time.sleep(1)
ser.write(b'r')
time.sleep(0.3)
ser.write(b'h')
time.sleep(0.3)
ser.write(b'r')
time.sleep(0.3)
ser.write(b'h')
time.sleep(0.3)
ser.write(b'r')
time.sleep(0.3)
ser.write(b'h')
time.sleep(0.3)
ser.write(b'r')
time.sleep(0.3)
ser.write(b'h')
time.sleep(0.3)
ser.write(b'l')
time.sleep(0.3)
ser.write(b'h')
time.sleep(0.3)
ser.write(b'l')
time.sleep(0.3)
ser.write(b'h')
time.sleep(0.3)
ser.write(b'l')
time.sleep(0.3)
ser.write(b'l')
time.sleep(0.3)
ser.write(b'h')
time.sleep(0.3)
ser.write(b'f')
time.sleep(0.5)
ser.write(b'b')
time.sleep(0.5)
ser.write(b'f')
time.sleep(0.5)
ser.write(b'b')
time.sleep(0.5)
ser.write(b'f')
time.sleep(0.5)
ser.write(b'b')
time.sleep(0.5)



ser.write(b'f')
time.sleep(0.5)
ser.write(b'b')
time.sleep(0.5)
ser.write(b'l')
time.sleep(0.5)
ser.write(b'r')
time.sleep(0.5)
ser.write(b'h')
time.sleep(0.5)
ser.write(b'f')
time.sleep(0.5)
ser.write(b'b')
time.sleep(0.5)
ser.write(b'l')
time.sleep(0.5)
ser.write(b'r')
time.sleep(0.5)
ser.write(b'h')
time.sleep(0.5)


